Cart/urls.py
from django.urls import path

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
)

app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<id>/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name='purchase_success'),
    path('item/delete/<item_id>/', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name='checkout'),
    path('update-transaction/<id>/', update_transaction_records, name='update_records')
]

Kleider/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Home.urls')),
    path('admin/', admin.site.urls),
    path('Kleider/', include('Home.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
from django.db import models
import os
import random
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.dispatch import receiver
from django.db.models.signals import post_save


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1,1000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "users/{final_filename}".format(final_filename=final_filename)


class Contact(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    content = models.TextField(default='')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Enter valid phone number must be entered in the format: '+9999999999'.")
    tel = models.CharField(validators=[phone_regex], max_length=15, blank=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Enter valid phone number must be entered in the format: '+9999999999'.")
    GENDER_CHOICES = (
        ('M', 'Male',),
        ('F', 'Female',),
        ('O', 'Other',),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    tel = models.CharField(validators=[phone_regex], max_length=15, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,)
    birth_date = models.DateField(null=True, blank=True)
    img = models.ImageField(upload_to=upload_image_path, null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender,instance,created, **kwargs):
    if created:
        Profile.objects.create(user = instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance , **kwargs):
    instance.profile.save()


class Help(models.Model):
    content = models.TextField(default='')

    def __str__(self):
        return self.content


class Feedback(models.Model):
    content = models.TextField(default='')
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.content

Products/models.py
from django.db import models
from Home.models import Profile
import os
import random
from django.db.models.signals import pre_save
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, SmartResize
from Kleider.utils import unique_slug_generator


# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 1000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "users/{final_filename}".format(final_filename=final_filename)


class Product(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male',),
        ('F', 'Female',),
    )
    PRODUCT_FOR_CHOICES = (
        ('sell', 'Sell',),
        ('rent', 'Rent',),
    )
    PRODUCT_TYPE_CHOICES = (
        ('cloths', 'Cloths',),
        ('accessories', 'Accessories',),
    )
    CONDITION_CHOICES = (
        ('used', 'Used'),
        ('new', 'New')
    )
    CATEGORY_CHOICES = (
        ('traditional', 'Traditional'),
        ('formal', 'Formal'),
        ('casual', 'Casual'),
        ('ethnic', 'Ethnic'),
        ('sports', 'Sports'),
        ('western', 'Western'),
        ('t-shirts', 'T-shirts'),
        ('denim', 'Denim'),
        ('kids', 'Kids'),
        ('winter-wears', 'Winter-wear'),
        ('jumpsuits', 'Jumpsuits'),
    )
    OCCASION_CHOICES = (
        ('weddings', 'Weddings'),
        ('sangeet', 'Sangeet'),
        ('party', 'Party'),
        ('everyday', 'Everyday'),
        ('interview', 'Interview'),
        ('gym', 'Gym'),
        ('outings', 'Outings'),
    )
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    product_for = models.CharField(max_length=4, choices=PRODUCT_FOR_CHOICES)
    slug = models.SlugField(blank=True, unique=True)
    type = models.CharField(max_length=11, choices=PRODUCT_TYPE_CHOICES)
    price = models.DecimalField(max_digits=10, decimal_places=2, default='99.99')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    condition = models.CharField(max_length=4, choices=CONDITION_CHOICES)
    category = models.CharField(max_length=17, choices=CATEGORY_CHOICES)
    occasion = models.CharField(max_length=9, choices=OCCASION_CHOICES)
    featured = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True)
    sold = models.BooleanField(default=False)
    image1 = models.ImageField(upload_to=upload_image_path)
    image2 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image3 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    image4 = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    smart1 = ImageSpecField(source='image1', processors=[ResizeToFill(250, 250)], format='JPEG', options={'quality': 99})
    smart2 = ImageSpecField(source='image2', processors=[SmartResize(250, 250)], format = 'JPEG', options={'quality': 99})
    smart3 = ImageSpecField(source='image3', processors=[SmartResize(250, 250)], format = 'JPEG', options={'quality': 99})
    smart4 = ImageSpecField(source='image4', processors=[SmartResize(250, 250)], format = 'JPEG', options={'quality': 99})

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Product'

    def get_absolute_url(self):
        return reverse('detail', kwargs={"slug": self.slug})


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)

templates/aboutus.html
{% load static %}
{% include 'common/header.html' %}

<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href='{% url "home" %}'><i class="fa fa-home home_1"></i></a> / <span>About us</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->

<h2 class="w3-head" style="text-align: center;border-bottom: 1px solid #f0f0f0;">About us</h2>
<br>
<br>
<p style="text-align: center;margin-left: 20%;margin-right: 20%">We believe fashion is for everyone. And don’t let your wallet tell you any different. Founded in 2019, Cloths was conceptualized to bring a simple vision to life; make runway-ready styles available to you at the click of a button.</p>
<br>
<p style="text-align: center;margin-left: 20%;margin-right: 20%">With a finger on the pulse of the latest trends, we asked your favourite celebrity stylists, bloggers, and influencers, to handpick and curate timeless classics for that envious Instagram feed. Dreading the wedding? Stay-cation on the cards? Or is it just the mid-week blues? Look no further. With a wide selection of ethnic and contemporary classics, consider this your one-stop shop for all occasions.</p>
<br>
<p style="text-align: center;margin-left: 20%;margin-right: 20%">We like to keep it: Elegant, Effortless and Edgy. And did we mention, Easy! Give your sedentary staples a prim revival and have them delivered straight to your doorstep. Didn’t you hear, convenient is the new chic?</p>



{% include 'common/footer.html' %}

templates/days.html
{% load static %}

<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'home'%}"><i class="fa fa-home home_1"></i></a> / <span>Days</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

{{ form }}










{% include 'common/footer.html' %}

templates/delete.html
{% load static %}
{% include 'common/header.html' %}


<section>
    <div id="agileits-sign-in-page" class="sign-in-wrapper">
        <div class="agileinfo_signin">
            <form method="post">{% csrf_token %}
                <h3 class="confirm_logout_info">Are you sure Want to delete "{{ object }}" ?</h3>
                <input type="submit" value="Submit" />
            </form>
        </div>
    </div>
</section>

{% include 'common/footer.html' %}

templates/faq.html
{% load static %}
{% include 'common/header.html' %}

<body>
	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'home' %}"><i class="fa fa-home home_1"></i></a> / <span>Faq</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

	<!-- Faq -->
	<div class="faq main-grid-border">
		<div class="container">
			<h2 class="w3-head">Faq's</h2>
			<dl class="faq-list">
				<dt class="faq-list_h">
				<h4 class="marker">Q?</h4>
				<h5 class="marker_head">How soon will my order reach me?</h5>
				</dt>
				<dd>
				<h4 class="marker1">A.</h4>
				<p class="m_13">Depending on your location, your order should reach you within 7 working days.</p>
				</dd>
				<!---728x90--->

				<dt class="faq-list_h">
				<h4 class="marker">Q?</h4>
				<h5 class="marker_head">Is there an additional cost for shipping?</h5>
				</dt>
				<dd>
				<h4 class="marker">A.</h4>
				<p class="m_13">No, we provide free shipping on all domestic orders.</p>
				</dd>
				<dt class="faq-list_h">
				<h4 class="marker">Q?</h4>
				<h5 class="marker_head">What is the security deposit?</h5>
				</dt>
				<dd>
				<h4 class="marker">A.</h4>
				<p class="m_13">Every time you reserve an outfit you will be asked to pay a security deposit that is equal to the rental price of your outfit. For example, if your outfit costs ₹5,000, we will add a security deposit of ₹5,000 to your bill, making the total ₹10,000. Since all our garments are authentic designer pieces, the security deposit is just standard protocol and serves as an insurance cover for our outfits whilst they are with you.</p>
				</dd>
				<!---728x90--->

				<dt class="faq-list_h">
				<h4 class="marker">Q?</h4>
				<h5 class="marker_head">What is the condition of the garment?</h5>
				</dt>
				<dd>
				<h4 class="marker">A.</h4>
				<p class="m_13">These garments are pre-owned designer wear clothes sourced from our reliable network of fashionistas or never worn sample pieces sourced directly from the designers. We have categorised the garments under 4 types: New, As Good As New, Gently used and Adequately Used.</p>
				</dd>
				<dt class="faq-list_h">
				<h4 class="marker">Q?</h4>
				<h5 class="marker_head">Can I pay for the garment in cash?</h5>
				</dt>
				<dd>
				<h4 class="marker">A.</h4>
				<p class="m_13">Sorry, but all payments can only be made online.</p>
          </dl>

		</div>	
	</div>
	<!-- // Faq -->

		<!-- Navigation-JavaScript -->
			<script src="js/classie.js"></script>
			<script src="js/main.js"></script>
		<!-- //Navigation-JavaScript -->
		<!-- here stars scrolling icon -->
			<script type="text/javascript">
				$(document).ready(function() {
					/*
						var defaults = {
						containerID: 'toTop', // fading element id
						containerHoverID: 'toTopHover', // fading element hover id
						scrollSpeed: 1200,
						easingType: 'linear' 
						};
					*/
										
					$().UItoTop({ easingType: 'easeOutQuart' });
										
					});
			</script>
			<!-- start-smoth-scrolling -->
			<script type="text/javascript" src="js/move-top.js"></script>
			<script type="text/javascript" src="js/easing.js"></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){		
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
					});
				});
			</script>
			<!-- start-smoth-scrolling -->
		<!-- //here ends scrolling icon -->
</body>

<!-- Mirrored from p.w3layouts.com/demos/aug-2016/24-08-2016/resale_v2/web/faq.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 30 Oct 2018 11:01:40 GMT -->
{% include 'common/footer.html' %}

templates/list.html
{% load static %}
{% load imagekit %}
{% include 'common/header.html' %}
<style>
    #delete {
        border-radius: 3px;
        display: inline-block;
        position: relative;
    }
    #edit {
        border-radius: 3px;
        display: inline-block;
        position: absolute;
        right: 115px;
      }
    #rent {
        border-radius: 3px;
        display: inline-block;
        position: absolute;
        right: 30px;
    }
</style>

<style>
    #cart {
        border-radius: 3px;
    }
    #remove {
        border-radius: 3px;
        display: inline-block;
        position: relative;
    }
    #in {
        border-radius: 3px;
        display: inline-block;
        position: absolute;
        right: 100px;
      }
</style>



	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="{% url 'home' %}">
                <i class="fa fa-home home_1"></i></a> / <span>All Ads</span>
            </span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="agileits-sear-head">Name contains</h3>
					<form method="get" action="{% url 'search' %}">
						<input type="text" name="product" value="Product Name or Category..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
						<input type="submit" value=" ">
					</form>
				</div>


                </div>
				<div class="agileinfo-ads-display col-md-9">
					<div class="wrapper">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <ul id="myTab" class="nav nav-tabs nav-tabs-responsive" role="tablist">
						<li role="presentation" class="active">
						  <a href="{% url 'home' %}" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">
							<span class="text">All Ads</span>
						  </a>
						</li>
					  </ul>
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
                               <div id="container">

							<ul class="list">
                            {% if object_list %}
                                {% for product in object_list %}
                                    {% if product.sold == False %}
                                        <li>
											#if {{ MEDIA_URL }} in there and throws error then remove it
											#and not available then add {{ MEDIA_URL }}
                                        <img src='{{ MEDIA_URL }}{{ product.smart1.url }}' title="" alt="" />
                                        <section class="list-left">
                                        <h4 class="title">{{ product.title }}</h4>
                                        <span class="adprice">Rs. {{ product.price }}</span>
                                        <p class="catpath">{{ product.get_category_display }} » {{ product.title }}</p>
                                            <p>{{ product.timestamp|timesince }} ago</p>
                                        </section>
                                        <section class="list-right">
                                        <span class="cityname"><strong>For {{ product.get_occasion_display }}</strong></span>
                                        <span class="adprice">{{ product.get_condition_display }}</span>
                                        {% if product.product_for == "sell" %}
                                             <span class="adprice">For Sell</span>
                                        {% else %}
                                            <span class="adprice">For Rent</span>
                                        {% endif %}
                                                <br/>
                                                {% if product.user == request.user.profile %}
                                                    <a href='{% url "edit" product.id %}'><input type="submit" id="edit" value="Edit" class="btn btn-info"></a>
                                                    <a href='{% url "delete" product.id %}'><input type="submit" id="delete" value="Delete" class="btn btn-danger"></a>
                                                {% elif product in current_order_products %}
                                                    <a href="{% url 'cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                                                {% else %}
                                                    <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>
                                                {% endif %}

                                            {% endif %}
                                        </section>
                                        <div class="clearfix"></div>
                                        </li>

                                {% endfor %}
                            {% else %}
                                <h2>No entries found</h2>
                            {% endif %}
							</ul>
						</div>
							</div>
						</div>
						<div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
						 <div>
                             <div id="container">
								<div class="view-controls-list" id="viewcontrols">
									<label>view :</label>
									<a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
									<a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
								</div>
                             </div>
                         </div>
						</div>
                        {% if object_list.has_other_pages %}
                          <ul class="pagination">
                            {% if object_list.has_previous %}
                              <li><a href="?page={{ object_list.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in object_list.paginator.page_range %}
                              {% if object_list.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if object_list.has_next %}
                              <li><a href="?page={{ object_list.next_page_number }}">&raquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                          </ul>
                        {% endif %}
                      </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- // Products -->
		<!-- Navigation-JavaScript -->
<!-- switcher-grid and list alignment -->
<script src='{% static "js/tabs.js" %}'></script>
<script type="text/javascript">
$(document).ready(function () {
    var elem=$('#container ul');
	$('#viewcontrols a').on('click',function(e) {
		if ($(this).hasClass('gridview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('list').addClass('grid');
				$('#viewcontrols').removeClass('view-controls-list').addClass('view-controls-grid');
				$('#viewcontrols .gridview').addClass('active');
				$('#viewcontrols .listview').removeClass('active');
				elem.fadeIn(1000);
			});
		}
		else if($(this).hasClass('listview')) {
			elem.fadeOut(1000, function () {
				$('#container ul').removeClass('grid').addClass('list');
				$('#viewcontrols').removeClass('view-controls-grid').addClass('view-controls-list');
				$('#viewcontrols .gridview').removeClass('active');
				$('#viewcontrols .listview').addClass('active');
				elem.fadeIn(1000);
			});
		}
	});
});
</script>
<!-- //switcher-grid and list alignment -->
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('flexbar', 'CKYI627U', 'placement:w3layoutscom');
  	}
})();
</script>
<script>
(function(){
if(typeof _bsa !== 'undefined' && _bsa) {
	// format, zoneKey, segment:value, options
	_bsa.init('fancybar', 'CKYDL2JN', 'placement:demo');
}
})();
</script>
<script>
(function(){
	if(typeof _bsa !== 'undefined' && _bsa) {
  		// format, zoneKey, segment:value, options
  		_bsa.init('stickybox', 'CKYI653J', 'placement:w3layoutscom');
  	}
})();
</script><script>
	(function(v,d,o,ai){ai=d.createElement("script");ai.defer=true;ai.async=true;ai.src=o;d.head.appendChild(ai);})(window, document, "https://vdo.ai/core/w3layouts/vdo.ai.js");
	</script><!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125810435-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125810435-1');
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-30027142-1', 'w3layouts.com');
  ga('send', 'pageview');
</script>
			<script src='{% static "js/classie.js" %}'></script>
			<script src='{% static "js/main.js" %}'></script>
		<!-- //Navigation-JavaScript -->
		<!-- here stars scrolling icon -->
			<script type="text/javascript">
				$(document).ready(function() {
					/*
						var defaults = {
						containerID: 'toTop', // fading element id
						containerHoverID: 'toTopHover', // fading element hover id
						scrollSpeed: 1200,
						easingType: 'linear'
						};
					*/

					$().UItoTop({ easingType: 'easeOutQuart' });

					});
			</script>
			<!-- start-smoth-scrolling -->
			<script type="text/javascript" src='{% static "js/move-top.js" %}'></script>
			<script type="text/javascript" src='{% static "js/easing.js" %}'></script>
			<script type="text/javascript">
				jQuery(document).ready(function($) {
					$(".scroll").click(function(event){
						event.preventDefault();
						$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
					});
				});
			</script>
			<!-- start-smoth-scrolling -->
		<!-- //here ends scrolling icon -->


<script>
    // Cart + Add Products
    var productForm = $(".form-product-ajax");
    productForm.submit(function(event){
        event.preventDefault();
        var thisForm = $(this);
        var actionEndpoint = thisForm.attr("action");
        var httpMethod = thisForm.attr("method");
        var formData = thisForm.serialize();

        $.ajax({
            url: actionEndpoint,
            method: httpMethod,
            data: formData,
            success: function(data){
                var submitSpan = thisForm.find(".submit-span");
                if (data.added){
                    submitSpan.html("<div class='btn-group'> <a id='in' class='btn btn-info'>In cart</a> <button type='submit' id='remove' class='btn btn-danger'>Remove?</button></div>")
                } else {
                    submitSpan.html("<button type='submit' id='cart' class='btn btn-success'>Add to cart</button>")
                }
                var cartCount = $(".cart-items");
                    cartCount.text(data.cartItemCount);
                },
            error: function (errorData) {
                console.log("Error");
                console.log(errorData)
            }
        })
    })
</script>
{% include 'common/footer.html' %}

templates/single.html
{% load static %}
{% include 'common/header.html' %}
	<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs">
			<a href='{% url "home" %}'><i class="fa fa-home home_1"></i></a>
			<a href="all-classifieds.html">All Ads</a> /
			<a href="cars.html">{{ object.category.title }}</a> /
			<span>{{ object.title }}</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!---728x90--->

	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<div class="product-desc">
				<div class="col-md-7 product-view">
                    <h2>{{ object.title }}</h2>
					<p> Ad ID: {{ object.id }}</p>
					<div class="flexslider">
						<ul class="slides">
							<li data-thumb="{{ object.smart1.url }}">
								<img src="{{ object.smart1.url }}" />
							</li>
                            {% if object.image2 %}
							<li data-thumb="{{ object.smart2.url }}">
								<img src="{{ object.smart2.url }}" />
							</li>
                            {% endif %}
                            {% if object.image3 %}
							<li data-thumb="{{ object.smart3.url }}">
								<img src="{{ object.smart3.url }}" />
							</li>
                            {% endif %}
                            {% if object.image4 %}
							<li data-thumb="{{ object.smart4.url }}">
								<img src="{{ object.smart4.url }}" />
							</li>
                            {% endif %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src='{% static "js/jquery.flexslider.js" %}'></script>

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4><span class="w3layouts-agileinfo">Best For </span> : <strong>{{ object.get_occasion_display }}</strong></h4>
						<h4><span class="w3layouts-agileinfo">Suits on </span> : {{ object.get_gender_display }}</h4>
						<h4><span class="w3layouts-agileinfo">Description </span> :<p>{{ object.description }}</p><div class="clearfix"></div></h4>

					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">Rs. {{ object.price }}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{ object.get_condition_display }}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{ object.get_category_display }}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p>{{ object.user.user }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp<i class="glyphicon glyphicon-earphone"></i>{{ object.user.tel }}</p>
					</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>

{% include 'common/footer.html' %}