Cart/urls.py
from django.urls import path

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
)

app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<id>/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name='purchase_success'),
    path('item/delete/<item_id>/', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name='checkout'),
    path('update-transaction/<id>/', update_transaction_records, name='update_records')
]

Kleider/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('Home.urls')),
    path('admin/', admin.site.urls),
    path('Kleider/', include('Home.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from __future__ import unicode_literals
from django.db import models
from Home.models import Profile
from Products.models import Product
from decimal import Decimal

# Create your models here.
class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user.profile
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user.profile
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    days = models.DecimalField(decimal_places=2, max_digits=10, max_length=20, default=1)

    def __str__(self):
        return self.product.title


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        price = Decimal(0.00)
        for item in self.items.all():
            if item.product.product_for == 'rent':
                price += Decimal(item.product.price) * int(item.days) * 2
            else:
                price += Decimal(item.product.price) * int(item.days)
        return price

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

Cart/forms.py
from django.forms import ModelForm
from .models import OrderItem


class RentdaysForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ['days']

Cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from Home.models import Profile
from Products.models import Product
from .extras import generate_order_id, transact, generate_client_token
from .models import OrderItem, Order, Transaction
import datetime
from .forms import RentdaysForm


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Product.objects.filter(id=kwargs.get('id', "")).first()
    # check if the user already owns this product
    # if product in request.user.profile.product_set.all():
    #     messages.info(request, 'You already own this Product')
    #     return redirect(reverse('list'))
    #     # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(reverse('cart:order_summary'))


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    order_items = existing_order.items.all() if existing_order!=0 else {}

    form = RentdaysForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
    else:
        form = RentdaysForm()

    context = {
        'order': existing_order,
        'order_items': order_items,
        'form': form,
    }
    return render(request, 'carts/order_summary.html', context)


@login_required()
def checkout(request, **kwargs):
    client_token = generate_client_token()
    existing_order = get_user_pending_order(request)
    if request.method == 'POST':
        result = transact({
        'amount': existing_order.get_cart_total(),
        'payment_method_nonce': request.POST['payment_method_nonce'],
        'options': {
            "submit_for_settlement": True
        }
        })
        if result.is_success or result.transaction:
            return redirect(reverse('cart:update_records',
                    kwargs={
                        'id': result.transaction.id
                    })
            )
        else:
            for x in result.errors.deep_errors:
                messages.info(request, x)
                return redirect(reverse('cart:checkout'))

    context = {
        'order': existing_order,
        'client_token': client_token
    }

    return render(request, 'carts/checkout.html', context)


@login_required()
def update_transaction_records(request, id):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())
    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.save()

    # create a transaction
    transaction = Transaction(profile=request.user.profile,
                              token=id,
                              order_id=order_to_purchase.id,
                              amount=order_to_purchase.get_cart_total(),
                              success=True)
    # save the transaction (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('cart:purchase_success'))


def success(request, **kwargs):
    # a view signifying the transaction was successful
    return render(request, 'carts/purchase_success.html', {})

templates/carts/order_summary.html
{% load static %}
{% include 'common/header.html' %}

{% for order_item in order_items %}
    {% if order_item.product.product_for == 'rent' and order_item.days == 1 %}
        {{ form.as_p }}
    {% endif %}
{% endfor %}




 <section style="margin : 5%; margin-top:2%">
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}

        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.title }}
            <span class="pull-right">
              <a href="{% url 'cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fa fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{% if item.product.product_for == 'rent' %}{{ item.product.price }}*{{item.days}} {% else %}{{ item.product.price }}{% endif %}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>

        <td colspan= 1>
          Rs. <strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'cart:checkout' %}" class="pull-right btn btn-success">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>

   </div>
 </section>

{% block scripts %}

  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

templates/carts/purchase_success.html
{% load static %}
{% include 'common/header.html' %}

<br/><br/>
<h1 style="text-align: center;">Thank you for your purchase!</h1><br/>
<p style="text-align: center;"><button class="btn"><a href="{% url 'home' %}">Head back home</a></button></p>
<br/>

{% include 'common/footer.html' %}

templates/carts/stripe_default_form.html
<script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Justdjango"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>